version: '3.9'

services:
  nestjs_api:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: mysql_db
      DATABASE_PORT: 3307
      DATABASE_USER: gabriel
      DATABASE_PASSWORD: SenhaTeste
      DATABASE_NAME: 'url-shortener-db'
    depends_on:
      - mysql_db
    volumes:
      - ./src:/usr/src/app/src

  mysql_db:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: senharoot
      MYSQL_DATABASE: 'url-shortener-db'
      MYSQL_USER: gabriel
      MYSQL_PASSWORD: SenhaTeste
      MYSQL_TCP_PORT: 3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
